---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.7.1
  - 2.6.3
  - 2.5.5
before_install:
  - gem i rubygems-update -v '3.1.2' && update_rubygems
  - gem i bundler -v '1.17.3'
before_script:
  - bundle install --jobs=3 --retry=3
script:
  - bundle exec rspec
gemfile:
  - Gemfile
fast_finish: true
