---
sudo: false
language: ruby
cache: bundler
rvm:
  - 3.1.2
  - 3.0.4
  - 2.7.6
  - 2.6.10
before_install:
  - gem i rubygems-update -v '3.3.19' && update_rubygems
  - gem i bundler -v '2.3.19'
before_script:
  - bundle install --jobs=3 --retry=3
script:
  - bundle exec rspec
gemfile:
  - Gemfile
fast_finish: true
